var Class;
(function(){var a=false,b=/xyz/.test(function(){})?/\b_super\b/:/.*/;this.Class=function(){};Class.extend=function(c){var e=this.prototype;a=true;var i=new this;a=false;for(var g in c)i[g]=typeof c[g]=="function"&&typeof e[g]=="function"&&b.test(c[g])?function(l,o){return function(){var p=this._super;this._super=e[l];var v=o.apply(this,arguments);this._super=p;return v}}(g,c[g]):c[g];function j(){!a&&this.init&&this.init.apply(this,arguments)}j.prototype=i;j.constructor=j;j.extend=arguments.callee;return j}})();
var gvr={};gvr.core={};gvr.alert=function(a){alert(a)};gvr.DEBUG=false;gvr.debug=function(){gvr.DEBUG&&console.log.apply(window,arguments)};gvr.robot={};gvr.robot.NORTH="NORTH";gvr.robot.WEST="WEST";gvr.robot.SOUTH="SOUTH";gvr.robot.EAST="EAST";gvr.robot.LEFT_OF={};gvr.robot.LEFT_OF[gvr.robot.NORTH]=gvr.robot.WEST;gvr.robot.LEFT_OF[gvr.robot.WEST]=gvr.robot.SOUTH;gvr.robot.LEFT_OF[gvr.robot.SOUTH]=gvr.robot.EAST;gvr.robot.LEFT_OF[gvr.robot.EAST]=gvr.robot.NORTH;gvr.robot.OFFSET={NORTH:{x:0,y:1},SOUTH:{x:0,y:-1},EAST:{x:1,y:0},WEST:{x:-1,y:0}};
gvr.robot.Robot=Class.extend({init:function(a){this.y=this.x=1;this.world=a;this.direction=gvr.robot.NORTH;this.beepers=0;this.on=true},move:function a(){if(this.front_is_blocked())throw new Error("Ran into a wall");var b=gvr.robot.OFFSET[this.direction];this.x+=b.x;this.y+=b.y},turnleft:function a(){this.direction=gvr.robot.LEFT_OF[this.direction]},pickbeeper:function a(){var b=this.world.getBeepers(this.x,this.y);if(b>0){this.beepers+=1;this.world.setBeepers(this.x,this.y,b-1)}else throw new Error("No beepers to pick up.");
},putbeeper:function a(){if(this.beepers>0){this.beepers-=1;this.world.setBeepers(this.x,this.y,this.world.getBeepers(this.x,this.y)+1)}else throw new Error("No beepers in beeper bag.");},turnoff:function a(){this.on=false;gvr.alert("Robot turned off")},facing_north:function a(){return this.direction===gvr.robot.NORTH},facing_south:function a(){return this.direction===gvr.robot.SOUTH},facing_east:function a(){return this.direction===gvr.robot.EAST},facing_west:function a(){return this.direction===
gvr.robot.WEST},any_beepers_in_beeper_bag:function a(){return this.beepers>0},next_to_a_beeper:function a(){return this.world.getBeepers(this.x,this.y)>0},front_is_blocked:function a(){return this.world.getWall(this.x,this.y,this.direction)},left_is_blocked:function a(){return this.world.getWall(this.x,this.y,gvr.robot.LEFT_OF[this.direction])},right_is_blocked:function a(){var b=gvr.robot.LEFT_OF[gvr.robot.LEFT_OF[gvr.robot.LEFT_OF[this.direction]]];return this.world.getWall(this.x,this.y,b)},not_facing_north:function(){return!this.facing_north()},
not_facing_south:function(){return!this.facing_south()},not_facing_east:function(){return!this.facing_east()},not_facing_west:function(){return!this.facing_west()},no_beepers_in_beeper_bag:function a(){return!this.any_beepers_in_beeper_bag()},not_next_to_a_beeper:function a(){return!this.next_to_a_beeper()},front_is_clear:function a(){return!this.front_is_blocked()},left_is_clear:function a(){return!this.left_is_blocked()},right_is_clear:function a(){return!this.right_is_blocked()}});gvr.world={};
gvr.world.World=Class.extend({init:function(){this.robot=gvr.newRobot(this);this.walls={};this.beepers={}},setBeepers:function(a,b,c){if(c!==null)this.beepers[""+a+","+b]=c;else delete this.beepers[""+a+","+b]},getBeepers:function(a,b){return this.beepers[""+a+","+b]||0},getWallCoordinates:function(a,b,c){if(c===gvr.robot.WEST){c=gvr.robot.EAST;a-=1}else if(c===gvr.robot.SOUTH){c=gvr.robot.NORTH;b-=1}return{x:a,y:b,direction:c}},setWall:function(a,b,c,e){var i=this.getWallCoordinates(a,b,c),g=""+
i.x+","+i.y;this.walls[g]||(this.walls[g]={NORTH:false,EAST:false});this.walls[g][i.direction]=true;if(e!==null&&e>1){i=gvr.robot.OFFSET[c];this.setWall(a+i.y,b+i.x,c,e-1)}},getWall:function(a,b,c){a=this.getWallCoordinates(a,b,c);return(b=this.walls[""+a.x+","+a.y])&&b[a.direction]||a.x===0&&a.direction===gvr.robot.EAST||a.y===0&&a.direction===gvr.robot.NORTH||false}});gvr.renderer={};
gvr.renderer.Renderer=Class.extend({init:function(a,b){this.canvas=document.getElementById(a);this.context=this.canvas.getContext("2d");var c=this;if(typeof this.context.measureText==="undefined"&&typeof this.context.mozMeasureText!=="undefined")this.context.measureText=function(e){return{width:c.context.mozMeasureText(e)}};if(typeof this.context.fillText==="undefined"&&typeof this.context.mozDrawText!=="undefined")this.context.fillText=function(e){return c.context.mozDrawText(e)};this.world=b;this.startY=
this.startX=1;this.endY=this.endX=12;this.scale=40},getCanvasCoords:function(a,b){return{x:a*this.scale,y:b*this.scale}},renderBounderies:function(){this.context.fillStyle=this.startY===1?"red":"#aaffaa";var a=this.getCanvasCoords(this.startX,this.startY);this.context.fillRect(a.x,a.y,this.canvas.width,2);this.context.fillStyle=this.startX===1?"red":"#aaffaa";a=this.getCanvasCoords(this.startX,this.startY);this.context.fillRect(a.x,a.y,2,this.canvas.height)},renderCorners:function(){this.context.fillStyle=
"#000000";for(var a=2;a<=this.endX-this.startX+1;a++)for(var b=2;b<=this.endY-this.startY+1;b++){var c=this.getCanvasCoords(a,b);this.context.fillRect(c.x,c.y,4,4)}},renderRobot:function(){this.context.save();this.context.fillStyle="white";this.context.lineWidth=5;var a=this.getCanvasCoords(this.world.robot.x,this.world.robot.y);this.context.translate(a.x+this.scale/2,a.y+this.scale/2);a={NORTH:0,WEST:Math.PI/2,SOUTH:Math.PI,EAST:-Math.PI/2}[this.world.robot.direction];this.context.rotate(a);a=this.scale*
0.2;this.context.beginPath();this.context.moveTo(-this.scale/2+a,-this.scale/2+a);this.context.lineTo(this.scale/2-a,-this.scale/2+a);this.context.lineTo(0,this.scale/2-a);this.context.closePath();this.context.stroke();this.context.fill();this.context.restore()},renderCoordinates:function(){this.context.fillStyle="black";for(var a,b,c=this.startX;c<this.endX;c++){a=this.getCanvasCoords(c,this.startY-1);this.context.save();b=this.context.measureText(""+c).width;this.context.translate(a.x+this.scale/
2-b/2,a.y+this.scale/2);this.context.scale(1,-1);this.context.fillText(""+c,0,0);this.context.restore()}for(c=this.startY;c<this.endY;c++){a=this.getCanvasCoords(this.startX-1,c);this.context.save();b=this.context.measureText(""+c).width;this.context.translate(a.x+this.scale/2-b/2,a.y+this.scale/2-6);this.context.scale(1,-1);this.context.fillText(""+c,0,0);this.context.restore()}},renderWalls:function(){this.context.fillStyle="red";for(var a=this.startX;a<this.endX;a++)for(var b=this.startY;b<this.endY;b++){var c=
this.getCanvasCoords(a,b);this.world.getWall(a,b,gvr.robot.NORTH)&&this.context.fillRect(c.x,c.y+this.scale,this.scale,2);this.world.getWall(a,b,gvr.robot.EAST)&&this.context.fillRect(c.x+this.scale,c.y,2,this.scale)}},renderBeepers:function(){this.context.fillStyle="blue";this.context.strokeStyle="blue";for(var a=this.startX;a<this.endX;a++)for(var b=this.startY;b<this.endY;b++){var c=this.getCanvasCoords(a,b),e=this.scale*0.2,i=this.world.getBeepers(a,b);if(i>0){this.context.beginPath();this.context.arc(c.x+
this.scale/2,c.y+this.scale/2,this.scale/2-e,0,Math.PI*2,false);this.context.stroke();if(i<2){this.context.beginPath();this.context.arc(c.x+this.scale/2,c.y+this.scale/2,this.scale/2-e-3,0,Math.PI*2,false);this.context.fill()}else{this.context.save();e=this.context.mozMeasureText(""+i);this.mozTextStyle="10px sans-serif";this.context.translate(c.x+this.scale/2-e/2,c.y+this.scale/2-6);this.context.scale(1,-1);this.context.mozDrawText(""+i);this.context.restore()}}}},followRobot:function(){var a=this.endX-
1,b=this.endY-1,c=0,e=0;if(this.world.robot.x>a)c=this.world.robot.x-a;else if(this.world.robot.x<this.startX)c=this.world.robot.x-this.startX;if(this.world.robot.y>b)e=this.world.robot.y-b;else if(this.world.robot.y<this.startY)e=this.world.robot.y-this.startY;this.startX+=c;this.endX+=c;this.startY+=e;this.endY+=e},render:function(){this.followRobot();this.context.save();this.context.clearRect(0,0,this.canvas.width,this.canvas.height);this.context.transform(1,0,0,-1,0,this.canvas.height);this.renderCorners();
this.context.save();this.context.translate(-(this.startX-1)*this.scale,-(this.startY-1)*this.scale);this.renderBounderies();this.renderWalls();this.renderBeepers();this.renderRobot();this.renderCoordinates();this.context.restore();this.context.restore()}});gvr.runner={Runner:Class.extend({init:function(a,b,c){this.program=a;this.stack=[this.program];this.renderer=b;this.globals={};this.globals[gvr.lang.RUNNER_GLOBAL_KEY]=this;this.timeout=null;this.notify=c||function(){};this.running=false},printStackTrace:function(){for(var a=[],b=0;b<this.stack.length;b++)a.push(this.stack[b].name);return a},step:function(a){this.run(0,a,true)},stop:function(){window.clearTimeout(this.timeout);this.running=false},run:function(a,b,c){this.running=true;var e=a===-1;
a=a||200;if(this.stack.length>0){var i=this.stack.pop();try{var g=i.step(this.globals)}catch(j){gvr.alert(j.message);return}this.stack=this.stack.concat(g);e||this.renderer.render();if(g.length>0){var l=this;if(e)this.run(a,b,c);else if(!c)this.timeout=window.setTimeout(function(){l.run(a,b,c)},a)}else this.run(a,b,c)}else{this.stop();if(this.renderer.world.robot.on){this.stop();gvr.alert("Robot ran out of instructions.")}typeof b==="function"&&b();e&&this.renderer.render()}}})};gvr.RunTimeError=function(a){this.message=a};gvr.newRobot=function(a){return new gvr.robot.Robot(a)};gvr.newWorld=function(){return new gvr.world.World};gvr.newRenderer=function(a,b){return new gvr.renderer.Renderer(a,b)};gvr.newRunner=function(a,b,c){return new gvr.runner.Runner(a,b,c)};gvr.i18n={};gvr.i18n.translationMap={};gvr.i18n.defaultLocale="en-US";gvr.i18n.locale=null;gvr.i18n.getBrowserLocale=function(){if(!gvr.i18n.locale&&navigator){var a=null;if(navigator.language)a=navigator.language;else if(navigator.browserLanguage)a=navigator.browserLanguage;else if(navigator.systemLanguage)a=navigator.systemLanguage;else if(navigator.userLanguage)a=navigator.userLanguage;gvr.i18n.locale=a?a.replace("_","-"):null}return gvr.i18n.locale||gvr.i18n.defaultLocale};
gvr.i18n.LocaleTranslation=Class.extend({init:function(a,b,c){this.locale=a;this.name=b;this.translations=c},getTranslation:function(a){return this.translations[a]}});gvr.i18n.registerTranslation=function(a,b,c){gvr.i18n.translationMap[a]=new gvr.i18n.LocaleTranslation(a,b,c)};
gvr.i18n.TranslatedString=Class.extend({init:function(a,b,c){this.messageId=a;this.defaultTranslation=b;this.locale=c||gvr.i18n.getBrowserLocale();this._cachedTranslation=null},getTranslation:function(){if(this._cachedTranslation)return this._cachedTranslation;var a=gvr.i18n.translationMap[this.locale];if(a)if(a=a.getTranslation(this.messageId))return this._cachedTranslation=a;return null},toString:function(){return this.getTranslation()||this.defaultTranslation}});
gvr.i18n.newTranslatedString=function(a,b,c){return new gvr.i18n.TranslatedString(a,b,c)};gvr.web={};gvr.web.client={};
gvr.web.client.Client=Class.extend({init:function(a){this.rootUrl=a||"/api"},logon:function(){window.location=this.rootUrl+"/logon?nextURL="+escape(window.location.href)},logout:function(){window.location=this.rootUrl+"/logout?nextURL="+escape(window.location.href)},post:function(a,b,c){jQuery.ajax({type:"POST",data:b,dataType:"json",url:a,success:c})},getUser:function(a){jQuery.getJSON(this.rootUrl+"/user",a)},getPrograms:function(a){jQuery.getJSON(this.rootUrl+"/programs",a)},getProgram:function(a,
b){jQuery.getJSON(this.rootUrl+"/programs/"+a,b)},addProgram:function(a,b){this.post(this.rootUrl+"/programs",a,b)},saveProgram:function(a,b){this.post(this.rootUrl+"/programs/"+a.key,a,b)},deleteProgram:function(a,b){jQuery.get(this.rootUrl+"/delete/"+a.key,b)},getWorlds:function(a){jQuery.getJSON(this.rootUrl+"/worlds",a)},getWorld:function(a,b){jQuery.getJSON(this.rootUrl+"/worlds/"+a,b)},addWorld:function(a,b){this.post(this.rootUrl+"/worlds",a,b)},saveWorld:function(a,b){this.post(this.rootUrl+
"/worlds/"+a.key,a,b)},deleteWorld:function(a,b){jQuery.get(this.rootUrl+"/delete/"+a.key,b)},getExamples:function(a){jQuery.getJSON(this.rootUrl+"/examples",a)},getExample:function(a,b){jQuery.getJSON(this.rootUrl+"/examples/"+a,b)},addExample:function(a,b){this.post(this.rootUrl+"/examples",a,b)},saveExample:function(a,b){this.post(a,this.rootUrl+"/examples/"+a.key,b)},deleteExample:function(a,b){jQuery.get(this.rootUrl+"/delete/"+a.key,b)}});gvr.web.client.newClient=function(a){return new gvr.web.client.Client(a)};gvr.lang={};gvr.lang.RUNNER_GLOBAL_KEY="$runner";gvr.lang.getRunner=function a(b){b=b||{};(b=b[gvr.lang.RUNNER_GLOBAL_KEY])||(b={notify:function(){}});return b};gvr.lang.BaseExpression=Class.extend({line:null,name:null,init:function(a,b){this.line=a;this.name=b}});
gvr.lang.Expression=gvr.lang.BaseExpression.extend({callable:null,scope:null,init:function(a,b,c){this._super(a,"expr");this.callable=b;this.scope=c},step:function(a){gvr.lang.getRunner(a).notify(this);try{this.callable.call(this.scope);return[]}catch(b){gvr.alert(b.message)}return null}});gvr.lang.newExpression=function(a,b,c){return new gvr.lang.Expression(a,b,c)};
gvr.lang.Block=Class.extend({init:function(a){this.name="block";this.expressions=a;this.currentStep=0},step:function(a){var b=[];if(this.currentStep<this.expressions.length){b.push(this);a=this.expressions[this.currentStep].step(a);this.currentStep++;b=b.concat(a)}else this.currentStep=0;return b}});
gvr.lang.If=gvr.lang.BaseExpression.extend({init:function(a,b,c,e){this._super(a,"if");this.callable=b;this.scope=c;this.block=new gvr.lang.Block(e);this.elifs=[];this.elseBlock=new gvr.lang.Block([])},step:function(a){gvr.lang.getRunner(a).notify(this);var b=false,c=[];if(this.callable.call(this.scope)){c=this.block.step(a);b=true}else if(this.elifs.length>0)for(var e=0;e<this.elifs.length;e++){var i=c.length;c=this.elifs[e].step(a);if(i!=c.length){b=true;break}}if(!b&&this.elseBlock.expressions.length>
0)c=this.elseBlock.step(a);return c}});gvr.lang.newIf=function(a,b,c,e){return new gvr.lang.If(a,b,c,e)};gvr.lang.While=gvr.lang.BaseExpression.extend({init:function(a,b,c,e){this._super(a,"while");this.callable=b;this.scope=c;this.block=new gvr.lang.Block(e)},step:function(a){gvr.lang.getRunner(a).notify(this);var b=[];if(this.callable.call(this.scope)){b.push(this);b=b.concat(this.block.step(a))}return b}});gvr.lang.newWhile=function(a,b,c,e){return new gvr.lang.While(a,b,c,e)};
gvr.lang.Do=gvr.lang.BaseExpression.extend({init:function(a,b,c){this._super(a,"do");this.count=b;this.block=new gvr.lang.Block(c);this.currentStep=0},step:function(a){gvr.lang.getRunner(a).notify(this);var b=[];if(this.currentStep<this.count){b.push(this);this.currentStep++;b=b.concat(this.block.step(a))}else this.currentStep=0;return b}});gvr.lang.newDo=function(a,b,c){return new gvr.lang.Do(a,b,c)};
gvr.lang.Define=gvr.lang.BaseExpression.extend({init:function(a,b,c){this._super(a,b);this.block=new gvr.lang.Block(c)},step:function(a){gvr.lang.getRunner(a).notify(this);a[this.name]=this;return[]}});gvr.lang.newDefine=function(a,b,c){return new gvr.lang.Define(a,b,c)};
gvr.lang.FunctionCall=gvr.lang.BaseExpression.extend({init:function(a,b){this._super(a,"call");this.fname=b},step:function(a){gvr.lang.getRunner(a).notify(this);if(!a[this.fname])throw new Error("The function "+this.fname+" is undefined.");return a[this.fname].block.step(a)}});gvr.lang.newFunctionCall=function(a,b){return new gvr.lang.FunctionCall(a,b)};gvr.lang.parser={};gvr.lang.parser.EXPRESSION=/^(\w*)\s*$/;gvr.lang.parser.DO=/^do\s*(\d+)\s*:\s*$/;gvr.lang.parser.IF=/^if\s*(\w+)\s*:\s*$/;gvr.lang.parser.ELIF=/^elif\s*(\w+)\s*:\s*$/;gvr.lang.parser.ELSE=/^else\s*:\s*$/;gvr.lang.parser.WHILE=/^while\s*(\w+)\s*:\s*$/;gvr.lang.parser.DEFINE=/^define\s*(\w+)\s*:\s*$/;gvr.lang.parser.EMPTY_LINE=/^\s*$/;gvr.lang.parser.INDENTATION=/^(\s*).*$/;gvr.lang.parser.removeComment=function(a){var b=a.indexOf("#");if(b>=0)a=a.slice(0,b);return a};
gvr.lang.parser.Parser=Class.extend({init:function(a,b){this.lines=a;this.robot=b;this.lineIndex=0},parse:function(){return new gvr.lang.Block(this.parseLines(""))},handlers:[function a(b,c,e){if(b=b.match(gvr.lang.parser.EXPRESSION)){b=b[1];gvr.debug(c+b);b in this.robot?e.push(gvr.lang.newExpression(this.lineIndex,this.robot[b],this.robot)):e.push(gvr.lang.newFunctionCall(this.lineIndex,b));return true}return false},function a(b,c,e){if(b=b.match(gvr.lang.parser.DO)){b=parseInt(b[1],10);gvr.debug(c+
"do "+b+":");e.push(gvr.lang.newDo(this.lineIndex,b,this.parseBlock()));return true}return false},function a(b,c,e){if(b=b.match(gvr.lang.parser.IF)){b=b[1];if(b in this.robot){gvr.debug(c+"if "+b+":");e.push(gvr.lang.newIf(this.lineIndex,this.robot[b],this.robot,this.parseBlock()));return true}}return false},function a(b,c,e){if((b=b.match(gvr.lang.parser.ELIF))&&e[e.length-1].name==="if"){b=b[1];gvr.debug(c+"elif "+b+":");e[e.length-1].elifs.push(gvr.lang.newIf(this.lineIndex,this.robot[b],this.robot,
this.parseBlock()));return true}return false},function a(b,c,e){if((b=b.match(gvr.lang.parser.ELSE))&&e[e.length-1].name==="if"){gvr.debug(c+"else:");e[e.length-1].elseBlock.expressions=this.parseBlock();return true}return false},function a(b,c,e){if(b=b.match(gvr.lang.parser.WHILE)){cond=b[1];if(cond in this.robot){gvr.debug(c+"while "+cond+":");e.push(gvr.lang.newWhile(this.lineIndex,this.robot[cond],this.robot,this.parseBlock()));return true}}return false},function a(b,c,e){if(b=b.match(gvr.lang.parser.DEFINE)){b=
b[1];gvr.debug(c+"define "+b+":");e.push(gvr.lang.newDefine(this.lineIndex,b,this.parseBlock()));return true}return false}],parseLines:function(a){for(var b=[];this.lineIndex<this.lines.length;this.lineIndex++){var c=gvr.lang.parser.removeComment(this.lines[this.lineIndex]);if(c.indexOf(a)!==0)break;else c=c.slice(a.length);if(!c.match(gvr.lang.parser.EMPTY_LINE)){for(var e=false,i=0;i<this.handlers.length;i++){var g=this.handlers[i];if(g.call(this,c,a,b)){e=true;break}}if(!e)throw new Error("Syntax Error on line "+
(this.lineIndex+1)+": "+c);}}return b},parseBlock:function(){var a=this.lines[++this.lineIndex];a=a.match(gvr.lang.parser.INDENTATION)[1];a=this.parseLines(a);this.lineIndex--;return a}});gvr.lang.parser.newParser=function(a,b){return new gvr.lang.parser.Parser(a,b)};gvr.world.parser={};gvr.world.parser.SPEC=/^\s*(\w+)\s+(\d+)\s+(\d+)\s+([NESW])\s+(\d+)?\s*$/;gvr.world.parser.BEEPERS=/^\s*(\w+)\s+(\d+)\s+(\d+)\s+(\d+)\s*$/;gvr.world.parser.EMPTY_LINE=gvr.lang.parser.EMPTY_LINE;
gvr.world.parser.Parser=Class.extend({init:function(a,b){this.lines=a;this.world=b},parse:function(){for(var a,b,c,e,i=0;i<this.lines.length;i++){var g=gvr.lang.parser.removeComment(this.lines[i]);if(!g.match(gvr.world.parser.EMPTY_LINE)){if(e=g.match(gvr.world.parser.SPEC)){a=e[1].toUpperCase();b=parseInt(e[2],10);c=parseInt(e[3],10);var j={N:"NORTH",S:"SOUTH",E:"EAST",W:"WEST"}[e[4]];e=parseInt(e[5],10)||1;if(a==="ROBOT"){this.world.robot.x=b;this.world.robot.y=c;this.world.robot.beepers=e;this.world.robot.direction=
j}a==="WALL"&&this.world.setWall(b,c,j,e)}if(g=g.match(gvr.world.parser.BEEPERS)){a=g[1].toUpperCase();if(a=="BEEPERS"){b=parseInt(g[2],10);c=parseInt(g[3],10);e=parseInt(g[4],10);this.world.setBeepers(b,c,e)}}}}}});gvr.world.parser.newParser=function(a,b){return new gvr.world.parser.Parser(a,b)};gvr.i18n.en_us={};
(function(){var a={"gvr-online":"GvR-Online!",home:"Home",browse:"Browse",logout:"Logout",login:"Login",program:"Program",help:"Help",dev:"Dev",speed:"Speed:",slow:"Slow",medium:"Medium",fast:"Fast",instant:"Instant","log-in-to-save":"Log in to save","log-in-to-create":"Log in to create new stuff","welcome-message":"Welcome to GvR-Online!","learn-about":"Learn about:",looping:"Looping","conditional-branching":"Conditional Branching","procedural-abstraction":"Procedural Abstraction","created-by":"Created by",
share:"Share","share-instructions":"Share this program and world with others.  Separate emails by a comma.","share-to":"To:","share-message-label":"Message:","see-your-example":"Click here to see your example.",welcome:"Welcome",execute:"Execute",stop:"Stop",step:"Step",reload:"Reload","code-editor":"Code Editor","world-editor":"World Editor",save:"Save","gvr-description":"GvR is an online tool to help teach beginning programming concepts.","checkout-example":"Check out a simple example:",run:"Run"};
gvr.i18n.registerTranslation("en-US","English",a)})();gvr.i18n.latin_pig={};
(function(){var a={"gvr-online":"GvRay-Onlinay!",home:"Omehay",browse:"Owsebray",logout:"Ogoutlay",login:"Oginlay",program:"Ogrampray",help:"Elphay",dev:"Evday",speed:"Eedspay:",slow:"Owslay",medium:"Ediummay",fast:"Astfay",instant:"Antinstay","log-in-to-save":"oglay inay otay avesay","log-in-to-create":"Oglay inay otay eatecray ewnay uffstay","welcome-message":"Elcomeway otay GvRay-Onlineay!","learn-about":"Earnlay aboutay:",looping:"Oopinglay","conditional-branching":"Conditional Branching","procedural-abstraction":"Onditionalcay Anchingbray",
"created-by":"Eatedcray byay",share:"Areshay","share-instructions":"Areshay isthay ogrampray anday orldway ithway othersay. Eparatesay emailsay byay aay ommacay.","share-to":"Otay:","share-message-label":"Essagemay:","see-your-example":"Ickclay erehay otay eesay ouryay exampleay.",welcome:"Elcomeway","gvr-description":"GvRay isay anay onlineay ooltay otay elphay eachtay eginningbay ogrammingpray onceptscay.","checkout-example":"Check out a simple example",run:"Unray",execute:"Executay",stop:"Opstay",
step:"Epstay",reload:"Eloadray","code-editor":"Odecay Editoray","world-editor":"Orldway Editoray",save:"avesay"};gvr.i18n.registerTranslation("latin-pig","Pig Latin",a)})();(function(){jQuery.fn.gvrDialog=function(a){var b=$("#templates .dialog").clone().addClass(a.cssClass||"").appendTo("body"),c=b.find(".window").append(this),e=($(document).width()-c.width())/2;c.css("left",e);b.find(".window-shadow").css("left",e+5);a.close&&$(a.close).click(function(){b.remove()});return this}})();
$(document).ready(function(){var a=gvr.web.client.newClient(),b=true,c="",e=false,i=null,g={},j={},l=null;function o(){return g[x]}function p(){return j[y]}function v(){function d(f,h){if(f){f.title=$("#"+h+"-editor-title").val();f.definition=$("#"+h+"-editor").val();f.description=$("#"+h+"-editor-description").val()}}d(o(),"program");d(p(),"world")}var r=gvr.newWorld();$(".panel .header .tab").click(function(){$(this).siblings().removeClass("selected");$(this).addClass("selected");var d=$(this).attr("id");
d=d.replace(/-tab$/,"");$("#"+d).siblings(".tab-content").hide();$("#"+d).show()});$("#logout-link").click(function(){a.logout()});$("#login-link").click(function(){a.logon()});function t(){if(l!==null&&l.running){$("#stop-button").removeAttr("disabled");$("#execute-button, #step-button").attr("disabled","disabled")}else{$("#stop-button").attr("disabled","disabled");$("#execute-button, #step-button").removeAttr("disabled")}}$("#execute-button").click(function d(){$("#reload-button").click();var f=
$("#program-editor").val().split("\n");try{var h=gvr.lang.parser.newParser(f,r.robot).parse(),k=gvr.newRenderer("canvas",r);l=gvr.newRunner(h,k);l.run(parseInt($("#speed").val()),function(){t()});t()}catch(m){gvr.alert(m.message);l.stop();t()}});$("#stop-button").click(function d(){l.stop();t()});$("#reload-button").click(function d(){var f=$("#world-editor").val().split("\n");r=gvr.newWorld();gvr.world.parser.newParser(f,r).parse();gvr.newRenderer("canvas",r).render()});var w={inStep:false};$("#step-button").click(function d(){if(!w.inStep){$("#reload-button").click();
var f=$("#program-editor").val().split("\n");try{var h=gvr.lang.parser.newParser(f,r.robot).parse(),k=gvr.newRenderer("canvas",r);l=gvr.newRunner(h,k,function(s){if(s.line){for(var z=0,q=0;q<s.line;q++)z+=f[q].length+1;q=$("#program-editor").get(0);q.selectionEnd=z+f[s.line].length;q.selectionStart=z;q.scrollTop=q.scrollHeight*s.line/f.length}})}catch(m){gvr.alert(m.message);w.inStep=false;l.stop()}w.inStep=true}l.step(function(){w.inStep=false;l.stop()})});$("#save-program").click(function(){gvr.alert("Saving...");
v();a.saveProgram(o(),function(){gvr.alert("Saved "+o().title)})});$("#save-world").click(function(){gvr.alert("Saving...");v();a.saveWorld(p(),function(){gvr.alert("Saved "+p().title)})});$("#new-world").click(A);$("#new-program").click(B);$("#share-button").click(function(){var d=p(),f=o();f&&d?$("#templates .share-form").clone().gvrDialog({cssClass:"share-form-dialog",close:'[name="cancel"]'}).find('[name="share"]').click(function(){var h=$(this).parents("form"),k={to:h.find('[name="share-to"]').val(),
message:h.find('[name="share-message"]').val(),world:d.key,program:f.key},m=h.find(".body.step-1");m.html($("#templates .loading-message").clone().find(".message").html("Sharing...").end());a.addExample(k,function(s){m.remove();$("<a>Click here to see your example.</a>").attr("href","index.html?example="+s.key+"#share").attr("target","_blank");h.find(".body.step-2").find("a.example-link").attr("href","index.html?example="+s.key+"#share").end().show()})}):gvr.alert("You must open a world and program before you can share them.")});
function C(){var d=gvr.newWorld();gvr.world.parser.newParser(["Robot 2 1 E 0","Beepers 1 1 1","Wall 9 1 E 2","Wall 2 3 E 2","Wall 9 5 E 3","Wall 1 7 N 9","Wall 3 2 N 7","Wall 3 4 N 7"],d).parse();var f=gvr.newRenderer("home-view-example-canvas",d);f.render();return{world:d,renderer:f}}$("#home-view-example-run-button").click(function(){var d=C(),f=$("#home-view-example-canvas-code").html().split("\n");f=gvr.lang.parser.newParser(f,d.world.robot).parse();d=gvr.newRunner(f,d.renderer);d.run(200)});
$(".file-description-editor").blur(function(){$(this).height(17).next().height(403)}).focus(function(){$(this).height(100).next().height(320)});function L(d){var f=$(d);d=f.attr("gvr:url");var h=f.attr("gvr:loaded"),k=f.attr("gvr:alwaysReload");if(d&&(!h||k)){$("#templates .loading-message").clone().appendTo(f);$.get(d,function(m){f.attr("gvr:loaded","loaded");f.html(m)})}}function D(d){L(d);$(d).show().siblings().hide()}function E(d){$("#navigation .selected").removeClass("selected");$(d).addClass("selected")}
function F(){n();E($("#navigation-browse"));D("#browse-view")}function G(){E(this);var d=$(this).attr("id").replace(/^navigation-/,"")+"-view";D("#"+d)}$("#navigation-browse").click(n);$.historyInit(function(d){if(d){var f=document.getElementById("navigation-"+d);f!==null?G.call(f):$.ajax({url:d+".html",success:function(h){$("#main").html(h)}})}else G.call(document.getElementById("navigation-home"))});$("a[rel='history']").click(function(){$.historyLoad(this.href.replace(/^.*#/,""));return false});
function M(d){a.getPrograms(function(f){for(var h=0;h<f.length;h++){var k=f[h];g[k.key]=k}n();typeof d==="function"&&d()})}function N(d){a.getWorlds(function(f){for(var h=0;h<f.length;h++){var k=f[h];j[k.key]=k}n();typeof d==="function"&&d()})}var u="World",O="Program",y=null,x=null;function A(){function d(f){j[f.key]=f;H(f);gvr.alert("Created new world")}a.addWorld({title:"Untitled World"},d)}function B(){function d(f){g[f.key]=f;I(f);gvr.alert("Created new program")}a.addProgram({title:"Untitled Program"},
d)}function J(d,f){$("#navigation-program").click();$("#"+f+"-editor").val(d.definition).show();$("#"+f+"-editor-title").val(d.title).show();$("#"+f+"-editor-description").val(d.description).show();$("#"+f+"-editor-pane-tab").click();$("#unopened-"+f+"-message").hide();e&&$("#save-"+f).removeAttr("disabled")}function H(d){J(d,"world");$("#world-editor-pane-tab").click();$("#reload-button").click();y=d.key}function I(d){J(d,"program");$("#program-editor-pane-tab").click();x=d.key}function P(){y=null;
$("#world-editor").hide();$("#world-editor-title").hide();$("#unopened-world-message").show();$("#save-world").attr("disabled","disabled")}function Q(){x=null;$("#program-editor").hide();$("#program-editor-title").hide();$("#unopened-program-message").show();$("#save-program").attr("disabled","disabled")}function R(d){d.type===u?H(d):I(d)}function S(d){if(confirm('Are you sure you want to delete "'+d.title+'"? This cannot be undone.'))d.type===u?a.deleteWorld(d,function(){d===p()&&P();delete j[d.key];
n();gvr.alert("Deleted "+d.title)}):a.deleteProgram(d,function(){d===o()&&Q();delete g[d.key];n();gvr.alert("Deleted "+d.title)})}function K(d){var f=$(d).closest(".file");d=f.attr("id");f=f.hasClass(u)?u:O;return f===u?j[d]:g[d]}function n(){var d=$("#browse-pane .file-browser .files");d.html("");function f(h){if(!(!b&&h.owner!=i.email))if(!(c&&!(h.title.toLowerCase().indexOf(c.toLowerCase())+1))){var k=o()===h||p()===h,m=$("#templates .file-browser .file").clone().attr("id",h.key).addClass(h.type).addClass(k?
"opened":"").appendTo(d);k=k?"*opened*":"";m.find("h1").text(h.title+" "+k);m.find("p").text(h.description);m.find(":button.open").click(function(){R(K(this))});m.find(":button.delete").click(function(){S(K(this))})}}for(id in g)f(g[id]);for(id in j)f(j[id]);d.find(".file:even").addClass("even")}gvr.alert=function(d){return $("#alert").text(d).show().fadeOut(5000)};a.getUser(function(d){if(d){i=d;e=true;$("#logout-link").show();$("#login-link").hide();$("#logon-nickname").text(d.nickname);$("#program-editor-pane .toolbar-top").show();
$("#world-editor-pane .toolbar-top").show();$('<a href="javascript:void(0)">create a new program</a>').click(B).insertAfter($("<span> or <span>").insertAfter($('<a href="javascript:void(0)">Browse existings programs</a>').click(F).insertAfter($("<div>No program is open.</div>").appendTo("#unopened-program-message"))));$('<a href="javascript:void(0)">create a new world</a>').click(A).insertAfter($("<span> or <span>").insertAfter($('<a href="javascript:void(0)">Browse existings worlds</a>').click(F).insertAfter($("<div>No world is open.</div>").appendTo("#unopened-world-message"))))}else{$("#share-button").hide();
$("#logout-link").hide();$("#login-link").show();$("#program-editor-pane :input, #world-editor-pane :input,").show();$("#world-editor-title").val("Temporary World");$("#program-editor-title").val("Temporary Program");function f(){a.logon()}$("#templates .login-to-save-message").clone().click(f).insertAfter($("#save-program").attr("disabled","disabled")).clone().click(f).insertAfter($("#save-world").attr("disabled","disabled"));$("#templates .login-to-create-new-stuff-message").clone().click(f).insertAfter($("#new-program"));
$("#new-world").attr("disabled","disabled");$("#new-program").attr("disabled","disabled")}M();N()});t();$("#reload-button").click();$("#show-my-files").click(function(){$(this).hide();$("#show-all-files").show();b=false;n()});$("#show-all-files").click(function(){$(this).hide();$("#show-my-files").show();b=true;n()});$("#search-files :input").keyup(function(){c=$(this).val();n()});C();$.each(gvr.i18n.translationMap,function(d,f){$("#language-selector").append('<option value="'+d+'">'+f.name+"</option>")});
$("#language-selector").val(gvr.i18n.getBrowserLocale());$("#language-selector").change(function(){gvr.i18n.locale=$(this).val();translate()});translate()});function translate(){var a=gvr.i18n.newTranslatedString;$("._").each(function(){var b=$(this).attr("i18n:id");$(this).html(a(b,$.trim($(this).html())).toString())})}
function i18nExtract(){var a={};$("._").each(function(){var b=gvr.i18n.newTranslatedString,c=$(this).attr("i18n:id");gvr.i18n.newTranslatedString(c).getTranslation()||(a[c]=$.trim($(this).html()))});$.getScript("http://www.json.org/json2.js",function(){});return a};
