// This file was autogenerated by calcdeps.py
goog.addDependency('lib/externs.js', [], []);
goog.addDependency('lib/gvr.core.js', ['gvr.core'], []);
goog.addDependency('lib/gvr.i18n.en_us.js', ['gvr.i18n.en_us'], ['gvr.i18n']);
goog.addDependency('lib/gvr.i18n.js', ['gvr.i18n'], []);
goog.addDependency('lib/gvr.i18n.latin_pig.js', ['gvr.i18n.latin_pig'], ['gvr.i18n']);
goog.addDependency('lib/gvr.js', ['gvr'], ['gvr.robot', 'gvr.world', 'gvr.renderer', 'gvr.runner']);
goog.addDependency('lib/gvr.lang.js', ['gvr.lang'], ['gvr.core']);
goog.addDependency('lib/gvr.lang.parser.js', ['gvr.lang.parser'], ['gvr.lang', 'gvr.core']);
goog.addDependency('lib/gvr.renderer.js', ['gvr.renderer'], ['gvr.core']);
goog.addDependency('lib/gvr.robot.js', ['gvr.robot'], ['gvr.core']);
goog.addDependency('lib/gvr.runner.js', ['gvr.runner'], ['gvr.core']);
goog.addDependency('lib/gvr.tests.js', [], []);
goog.addDependency('lib/gvr.web.client.js', ['gvr.web.client'], ['gvr.core']);
goog.addDependency('lib/gvr.web.tests.js', [], []);
goog.addDependency('lib/gvr.world.js', ['gvr.world'], ['gvr.core']);
goog.addDependency('lib/gvr.world.parser.js', ['gvr.world.parser'], ['gvr.core', 'gvr.lang.parser']);
goog.addDependency('lib/jquery.history.js', [], []);
goog.addDependency('lib/launcher.js', [], []);
